name: Generate Snake

on:
  schedule: 
    - cron: "0 */8 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verificar o repositório
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      # Criar diretório de saída, se necessário
      - name: Create dist directory
        run: mkdir -p dist

      # Gerar a animação da cobrinha
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: riqueandrade  # Substitua pelo seu nome de usuário
          outputs: dist/snake.svg

      # Adicionar a animação ao repositório
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push

      # Publicar a animação como artefato
      - name: Upload snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg
