name: Generate Snake

# Controle quando a ação será executada
on:
  schedule: # Executa a ação a cada 8 horas
    - cron: "0 */8 * * *"
  workflow_dispatch: # Permite executar o fluxo manualmente do GitHub

# Defina o que será feito
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verifique o repositório
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Gera a animação da cobrinha
      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: riqueandrade  # Substitua pelo seu nome de usuário no GitHub
          outputs: dist/snake.svg

      # Adiciona a animação gerada ao repositório
      - name: Commit and Push
        run: |
          git config --local user.name "riqueandrade"
          git config --local user.email "seu-email@example.com"
          git add -A
          git commit -m "Generated snake animation"
          git push

      # Publica a animação gerada como um artefato
      - name: Upload snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg
