name: Generate Snake

on:
  schedule:
    - cron: "0 */2 * * *"  # Atualiza a cada 2 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: riqueandrade
          outputs: dist/snake.svg

      - name: Push Snake
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
